<?php

namespace ROT\Bundle\IISBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\Persistence\ObjectManager;
use ROT\Bundle\IISBundle\Entity\Boot;

class LoadBoot extends AbstractFixture {
    public function load(ObjectManager $manager) {
        $boten = array(
            array('id' => '1','type' => 'a-cat large spi (1)','klasse' => 'default','normalrating' => '101','spinnakerrating' => '95','iscustom' => '0'),
            array('id' => '2','type' => 'a-cat (1)','klasse' => 'formule 18','normalrating' => '101','spinnakerrating' => '96','iscustom' => '0'),
            array('id' => '3','type' => 'bim 20 speciaal 2007','klasse' => 'default','normalrating' => '100','spinnakerrating' => '95','iscustom' => '0'),
            array('id' => '4','type' => 'bim javelin F18 HT','klasse' => 'default','normalrating' => '102','spinnakerrating' => '97','iscustom' => '0'),
            array('id' => '5','type' => 'blade F16 (2)','klasse' => 'default','normalrating' => '106','spinnakerrating' => '102','iscustom' => '0'),
            array('id' => '6','type' => 'C2','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '7','type' => 'capricorn F18','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '8','type' => 'cirrus F18','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '9','type' => 'coolcat 18','klasse' => 'default','normalrating' => '115','spinnakerrating' => '109','iscustom' => '0'),
            array('id' => '10','type' => 'dart 16','klasse' => 'default','normalrating' => '128','spinnakerrating' => '121','iscustom' => '0'),
            array('id' => '11','type' => 'dart 18 (1)','klasse' => 'default','normalrating' => '121','spinnakerrating' => '113','iscustom' => '0'),
            array('id' => '12','type' => 'dart 18 (2)','klasse' => 'default','normalrating' => '120','spinnakerrating' => '112','iscustom' => '0'),
            array('id' => '13','type' => 'dart 20','klasse' => 'default','normalrating' => '107','spinnakerrating' => '102','iscustom' => '0'),
            array('id' => '14','type' => 'dart hawk','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '15','type' => 'dominator','klasse' => 'default','normalrating' => '100','spinnakerrating' => '95','iscustom' => '0'),
            array('id' => '16','type' => 'eagle 18 carbon SL','klasse' => 'default','normalrating' => '103','spinnakerrating' => '98','iscustom' => '0'),
            array('id' => '17','type' => 'eagle 20 carbon','klasse' => 'default','normalrating' => '94','spinnakerrating' => '90','iscustom' => '0'),
            array('id' => '18','type' => 'eagle 20 carbon T','klasse' => 'default','normalrating' => '96','spinnakerrating' => '91','iscustom' => '0'),
            array('id' => '19','type' => 'eagle 20 Hilger','klasse' => 'default','normalrating' => '97','spinnakerrating' => '93','iscustom' => '0'),
            array('id' => '20','type' => 'eagle 20 strabr large','klasse' => 'default','normalrating' => '91','spinnakerrating' => '87','iscustom' => '0'),
            array('id' => '21','type' => 'eagle 20 strabr small','klasse' => 'default','normalrating' => '96','spinnakerrating' => '91','iscustom' => '0'),
            array('id' => '22','type' => 'eagle F20','klasse' => 'default','normalrating' => '101','spinnakerrating' => '96','iscustom' => '0'),
            array('id' => '23','type' => 'eagle strabr small no jib','klasse' => 'default','normalrating' => '102','spinnakerrating' => '96','iscustom' => '0'),
            array('id' => '24','type' => 'exploder 20','klasse' => 'default','normalrating' => '102','spinnakerrating' => '97','iscustom' => '0'),
            array('id' => '25','type' => 'exploder 20 carbon','klasse' => 'default','normalrating' => '98','spinnakerrating' => '93','iscustom' => '0'),
            array('id' => '26','type' => 'exploder F18','klasse' => 'default','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '27','type' => 'extreme 20','klasse' => 'default','normalrating' => '93','spinnakerrating' => '87','iscustom' => '0'),
            array('id' => '28','type' => 'extreme 20 BW code0','klasse' => 'default','normalrating' => '82','spinnakerrating' => '81','iscustom' => '0'),
            array('id' => '29','type' => 'extreme 20 BW spi','klasse' => 'default','normalrating' => '97','spinnakerrating' => '89','iscustom' => '0'),
            array('id' => '30','type' => 'extreme 20 NED1','klasse' => 'default','normalrating' => '92','spinnakerrating' => '87','iscustom' => '0'),
            array('id' => '31','type' => 'extreme 20 SW code0','klasse' => 'default','normalrating' => '83','spinnakerrating' => '83','iscustom' => '0'),
            array('id' => '32','type' => 'extreme 20 SW spi','klasse' => 'default','normalrating' => '101','spinnakerrating' => '92','iscustom' => '0'),
            array('id' => '33','type' => 'extreme 20 vs','klasse' => 'default','normalrating' => '91','spinnakerrating' => '87','iscustom' => '0'),
            array('id' => '34','type' => 'falcon F16 (1)','klasse' => 'default','normalrating' => '107','spinnakerrating' => '102','iscustom' => '0'),
            array('id' => '35','type' => 'falcon F16 (2)','klasse' => 'default','normalrating' => '106','spinnakerrating' => '102','iscustom' => '0'),
            array('id' => '36','type' => 'flaXcat proto 2 2003','klasse' => 'default','normalrating' => '112','spinnakerrating' => '107','iscustom' => '0'),
            array('id' => '37','type' => 'formule 16 (2)','klasse' => 'default','normalrating' => '106','spinnakerrating' => '102','iscustom' => '0'),
            array('id' => '38','type' => 'formule 18','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '39','type' => 'formule 18 Hightech','klasse' => 'default','normalrating' => '102','spinnakerrating' => '97','iscustom' => '0'),
            array('id' => '40','type' => 'formule 20','klasse' => 'formule 20','normalrating' => '101','spinnakerrating' => '96','iscustom' => '0'),
            array('id' => '41','type' => 'G-Cat 5.7','klasse' => 'default','normalrating' => '111','spinnakerrating' => '106','iscustom' => '0'),
            array('id' => '42','type' => 'hobie 14 (1)','klasse' => 'default','normalrating' => '136','spinnakerrating' => '128','iscustom' => '0'),
            array('id' => '43','type' => 'hobie 14s (1)','klasse' => 'default','normalrating' => '125','spinnakerrating' => '120','iscustom' => '0'),
            array('id' => '44','type' => 'hobie 16','klasse' => 'default','normalrating' => '118','spinnakerrating' => '112','iscustom' => '0'),
            array('id' => '45','type' => 'hobie 17 (1)','klasse' => 'default','normalrating' => '120','spinnakerrating' => '114','iscustom' => '0'),
            array('id' => '46','type' => 'hobie 17s (1)','klasse' => 'default','normalrating' => '112','spinnakerrating' => '108','iscustom' => '0'),
            array('id' => '47','type' => 'hobie 18','klasse' => 'default','normalrating' => '112','spinnakerrating' => '106','iscustom' => '0'),
            array('id' => '48','type' => 'hobie 18 form.','klasse' => 'default','normalrating' => '107','spinnakerrating' => '102','iscustom' => '0'),
            array('id' => '49','type' => 'hobie 18 magnum','klasse' => 'default','normalrating' => '112','spinnakerrating' => '106','iscustom' => '0'),
            array('id' => '50','type' => 'hobie 18 tiger','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '51','type' => 'hobie 20 fox','klasse' => 'formule 20','normalrating' => '101','spinnakerrating' => '96','iscustom' => '0'),
            array('id' => '52','type' => 'hobie fox concept','klasse' => 'default','normalrating' => '93','spinnakerrating' => '89','iscustom' => '0'),
            array('id' => '53','type' => 'hobie Fox extreme','klasse' => 'default','normalrating' => '100','spinnakerrating' => '96','iscustom' => '0'),
            array('id' => '54','type' => 'hobie fx one (1)','klasse' => 'default','normalrating' => '111','spinnakerrating' => '105','iscustom' => '0'),
            array('id' => '55','type' => 'hobie fx one (2)','klasse' => 'default','normalrating' => '109','spinnakerrating' => '105','iscustom' => '0'),
            array('id' => '56','type' => 'hobie max','klasse' => 'default','normalrating' => '123','spinnakerrating' => '117','iscustom' => '0'),
            array('id' => '57','type' => 'hobie pacific','klasse' => 'default','normalrating' => '110','spinnakerrating' => '106','iscustom' => '0'),
            array('id' => '58','type' => 'hobie tatoo','klasse' => 'default','normalrating' => '127','spinnakerrating' => '123','iscustom' => '0'),
            array('id' => '59','type' => 'hobie wild cat','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '60','type' => 'hunter 18','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '61','type' => 'hurricane 5.9','klasse' => 'default','normalrating' => '104','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '62','type' => 'hydra 16','klasse' => 'default','normalrating' => '123','spinnakerrating' => '115','iscustom' => '0'),
            array('id' => '63','type' => 'KL 17.5','klasse' => 'default','normalrating' => '118','spinnakerrating' => '111','iscustom' => '0'),
            array('id' => '64','type' => 'KL F18','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '65','type' => 'M18 (1)','klasse' => 'default','normalrating' => '99','spinnakerrating' => '95','iscustom' => '0'),
            array('id' => '66','type' => 'M20','klasse' => 'default','normalrating' => '98','spinnakerrating' => '92','iscustom' => '0'),
            array('id' => '67','type' => 'M20 AN1','klasse' => 'default','normalrating' => '97','spinnakerrating' => '91','iscustom' => '0'),
            array('id' => '68','type' => 'M20 GT / Large Spi','klasse' => 'default','normalrating' => '98','spinnakerrating' => '91','iscustom' => '0'),
            array('id' => '69','type' => 'M20 GTI large spi','klasse' => 'default','normalrating' => '93','spinnakerrating' => '88','iscustom' => '0'),
            array('id' => '70','type' => 'M20 HD1','klasse' => 'default','normalrating' => '94','spinnakerrating' => '89','iscustom' => '0'),
            array('id' => '71','type' => 'M20 JPS','klasse' => 'default','normalrating' => '90','spinnakerrating' => '86','iscustom' => '0'),
            array('id' => '72','type' => 'M20 RH1','klasse' => 'default','normalrating' => '99','spinnakerrating' => '95','iscustom' => '0'),
            array('id' => '73','type' => 'M20 RH3','klasse' => 'default','normalrating' => '106','spinnakerrating' => '99','iscustom' => '0'),
            array('id' => '74','type' => 'M20 RK1','klasse' => 'default','normalrating' => '103','spinnakerrating' => '95','iscustom' => '0'),
            array('id' => '75','type' => 'M20 RK2','klasse' => 'default','normalrating' => '97','spinnakerrating' => '91','iscustom' => '0'),
            array('id' => '76','type' => 'M20 Vampire','klasse' => 'default','normalrating' => '90','spinnakerrating' => '86','iscustom' => '0'),
            array('id' => '77','type' => 'M20 XP1','klasse' => 'default','normalrating' => '89','spinnakerrating' => '85','iscustom' => '0'),
            array('id' => '78','type' => 'mattia 18','klasse' => 'default','normalrating' => '107','spinnakerrating' => '102','iscustom' => '0'),
            array('id' => '79','type' => 'mattia F18','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '80','type' => 'miracle 6.0','klasse' => 'default','normalrating' => '104','spinnakerrating' => '99','iscustom' => '0'),
            array('id' => '81','type' => 'mystere 5.0 xl','klasse' => 'default','normalrating' => '116','spinnakerrating' => '110','iscustom' => '0'),
            array('id' => '82','type' => 'mystere 5.5','klasse' => 'default','normalrating' => '105','spinnakerrating' => '101','iscustom' => '0'),
            array('id' => '83','type' => 'nacra 18 (2)(3.3)','klasse' => 'default','normalrating' => '113','spinnakerrating' => '106','iscustom' => '0'),
            array('id' => '84','type' => 'nacra 18m2 (1)','klasse' => 'default','normalrating' => '103','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '85','type' => 'nacra 20 large','klasse' => 'default','normalrating' => '101','spinnakerrating' => '96','iscustom' => '0'),
            array('id' => '86','type' => 'nacra 4.5 (1)','klasse' => 'default','normalrating' => '123','spinnakerrating' => '118','iscustom' => '0'),
            array('id' => '87','type' => 'nacra 4.5 (1) jib','klasse' => 'default','normalrating' => '115','spinnakerrating' => '113','iscustom' => '0'),
            array('id' => '88','type' => 'nacra 4.5 (2)','klasse' => 'default','normalrating' => '122','spinnakerrating' => '116','iscustom' => '0'),
            array('id' => '89','type' => 'nacra 500 (2)','klasse' => 'default','normalrating' => '118','spinnakerrating' => '111','iscustom' => '0'),
            array('id' => '90','type' => 'nacra 570','klasse' => 'default','normalrating' => '110','spinnakerrating' => '105','iscustom' => '0'),
            array('id' => '91','type' => 'nacra 580(provisional)','klasse' => 'default','normalrating' => '108','spinnakerrating' => '101','iscustom' => '0'),
            array('id' => '92','type' => 'nacra 5.0 (2)','klasse' => 'default','normalrating' => '119','spinnakerrating' => '112','iscustom' => '0'),
            array('id' => '93','type' => 'nacra 5.2','klasse' => 'default','normalrating' => '111','spinnakerrating' => '105','iscustom' => '0'),
            array('id' => '94','type' => 'nacra 5.5 sl','klasse' => 'default','normalrating' => '106','spinnakerrating' => '101','iscustom' => '0'),
            array('id' => '95','type' => 'nacra 5.7','klasse' => 'default','normalrating' => '112','spinnakerrating' => '106','iscustom' => '0'),
            array('id' => '96','type' => 'nacra 5.8','klasse' => 'default','normalrating' => '106','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '97','type' => 'nacra 6.0','klasse' => 'default','normalrating' => '104','spinnakerrating' => '99','iscustom' => '0'),
            array('id' => '98','type' => 'nacra 6.0 SE 006-007','klasse' => 'default','normalrating' => '98','spinnakerrating' => '94','iscustom' => '0'),
            array('id' => '99','type' => 'nacra blast','klasse' => 'default','normalrating' => '122','spinnakerrating' => '117','iscustom' => '0'),
            array('id' => '100','type' => 'nacra F17 Sloop','klasse' => 'default','normalrating' => '109','spinnakerrating' => '104','iscustom' => '0'),
            array('id' => '101','type' => 'nacra F17 (1)','klasse' => 'default','normalrating' => '112','spinnakerrating' => '106','iscustom' => '0'),
            array('id' => '102','type' => 'nacra F18','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '103','type' => 'nacra F20 carbon','klasse' => 'default','normalrating' => '93','spinnakerrating' => '89','iscustom' => '0'),
            array('id' => '104','type' => 'nacra infusion','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '105','type' => 'nacra inter 17 (1)','klasse' => 'default','normalrating' => '115','spinnakerrating' => '108','iscustom' => '0'),
            array('id' => '106','type' => 'nacra inter 17 (1) jib','klasse' => 'default','normalrating' => '108','spinnakerrating' => '103','iscustom' => '0'),
            array('id' => '107','type' => 'nacra inter 17 (2)','klasse' => 'default','normalrating' => '113','spinnakerrating' => '107','iscustom' => '0'),
            array('id' => '108','type' => 'nacra inter 18','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '109','type' => 'nacra inter 20','klasse' => 'formule 20','normalrating' => '101','spinnakerrating' => '96','iscustom' => '0'),
            array('id' => '110','type' => 'piranha 17','klasse' => 'default','normalrating' => '114','spinnakerrating' => '108','iscustom' => '0'),
            array('id' => '111','type' => 'predator 20','klasse' => 'default','normalrating' => '102','spinnakerrating' => '95','iscustom' => '0'),
            array('id' => '112','type' => 'predator 20C','klasse' => 'default','normalrating' => '100','spinnakerrating' => '93','iscustom' => '0'),
            array('id' => '113','type' => 'prindle 15 (1)','klasse' => 'default','normalrating' => '125','spinnakerrating' => '119','iscustom' => '0'),
            array('id' => '114','type' => 'prindle 16','klasse' => 'default','normalrating' => '121','spinnakerrating' => '114','iscustom' => '0'),
            array('id' => '115','type' => 'prindle 18','klasse' => 'default','normalrating' => '115','spinnakerrating' => '109','iscustom' => '0'),
            array('id' => '116','type' => 'prindle 18-2','klasse' => 'default','normalrating' => '108','spinnakerrating' => '103','iscustom' => '0'),
            array('id' => '117','type' => 'prindle 18-2 torrig','klasse' => 'default','normalrating' => '106','spinnakerrating' => '101','iscustom' => '0'),
            array('id' => '118','type' => 'prindle 18 escape','klasse' => 'default','normalrating' => '116','spinnakerrating' => '109','iscustom' => '0'),
            array('id' => '119','type' => 'prindle 19','klasse' => 'default','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '120','type' => 'shockwave F18','klasse' => 'formule 18','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '121','type' => 'SL 16','klasse' => 'default','normalrating' => '120','spinnakerrating' => '115','iscustom' => '0'),
            array('id' => '122','type' => 'stealth F16 (2)','klasse' => 'default','normalrating' => '106','spinnakerrating' => '102','iscustom' => '0'),
            array('id' => '123','type' => 'stealth F18 HT','klasse' => 'default','normalrating' => '102','spinnakerrating' => '97','iscustom' => '0'),
            array('id' => '124','type' => 'supercat 17','klasse' => 'default','normalrating' => '112','spinnakerrating' => '107','iscustom' => '0'),
            array('id' => '125','type' => 'supercat 20 Texel','klasse' => 'default','normalrating' => '97','spinnakerrating' => '92','iscustom' => '0'),
            array('id' => '126','type' => 'swell spitfire','klasse' => 'default','normalrating' => '108','spinnakerrating' => '104','iscustom' => '0'),
            array('id' => '127','type' => 'swell spitfire RW','klasse' => 'default','normalrating' => '107','spinnakerrating' => '103','iscustom' => '0'),
            array('id' => '128','type' => 'topcat F2 (2)','klasse' => 'default','normalrating' => '127','spinnakerrating' => '120','iscustom' => '0'),
            array('id' => '129','type' => 'topcat k1 big jib','klasse' => 'default','normalrating' => '111','spinnakerrating' => '106','iscustom' => '0'),
            array('id' => '130','type' => 'topcat k2 (2)','klasse' => 'default','normalrating' => '114','spinnakerrating' => '108','iscustom' => '0'),
            array('id' => '131','type' => 'topcat k2 (2) small jib','klasse' => 'default','normalrating' => '115','spinnakerrating' => '109','iscustom' => '0'),
            array('id' => '132','type' => 'topcat K3 (1)','klasse' => 'default','normalrating' => '120','spinnakerrating' => '114','iscustom' => '0'),
            array('id' => '133','type' => 'topcat K3 (2)','klasse' => 'default','normalrating' => '119','spinnakerrating' => '112','iscustom' => '0'),
            array('id' => '134','type' => 'tornado','klasse' => 'default','normalrating' => '99','spinnakerrating' => '94','iscustom' => '0'),
            array('id' => '135','type' => 'tornado 420 (minicorn) (1)','klasse' => 'default','normalrating' => '124','spinnakerrating' => '118','iscustom' => '0'),
            array('id' => '136','type' => 'tornado classic','klasse' => 'default','normalrating' => '100','spinnakerrating' => '95','iscustom' => '0'),
            array('id' => '137','type' => 'ventilo 18','klasse' => 'default','normalrating' => '108','spinnakerrating' => '102','iscustom' => '0'),
            array('id' => '138','type' => 'viper (1)','klasse' => 'default','normalrating' => '110','spinnakerrating' => '105','iscustom' => '0'),
            array('id' => '139','type' => 'viper (2)','klasse' => 'default','normalrating' => '108','spinnakerrating' => '104','iscustom' => '0'),
            array('id' => '140','type' => 'White Formula 20','klasse' => 'default','normalrating' => '100','spinnakerrating' => '95','iscustom' => '0'),
            array('id' => '141','type' => 'Wildcat Lynx','klasse' => 'default','normalrating' => '109','spinnakerrating' => '104','iscustom' => '0'),
            array('id' => '142','type' => 'X19','klasse' => 'default','normalrating' => '102','spinnakerrating' => '97','iscustom' => '0'),
            array('id' => '143','type' => 'cirrus R','klasse' => 'formule 18, default','normalrating' => '105','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '144','type' => 'nacra 17 (2)','klasse' => 'default','normalrating' => '104','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '145','type' => '**Overig/Other**','klasse' => 'default','normalrating' => '100','spinnakerrating' => '100','iscustom' => '0'),
            array('id' => '146','type' => 'nacra F16 (2)','klasse' => 'default','normalrating' => '108','spinnakerrating' => '104','iscustom' => '0'),
            array('id' => '147','type' => 'nacra F16 (1)','klasse' => 'default','normalrating' => '110','spinnakerrating' => '105','iscustom' => '0')
        );

        foreach ($boten as $boot) {
            $b = new Boot();
            $b->setType($boot['type']);
            $b->setKlasse($boot['klasse']);
            $b->setNormalrating($boot['normalrating']);
            $b->setSpinnakerrating($boot['spinnakerrating']);
            $b->setIscustom($boot['iscustom']);
            $manager->persist($b);
            $this->addReference('boot-' . $boot['type'], $b);
        }

        $manager->flush();
    }
}