parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     rot
    database_user:     rot
    database_password: "password"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    dev_mailer_target: me@example.com

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
